name: EasierBot Assistant

on:
  schedule:
    - cron: '*/15 * * * *'
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  run-bot:
    uses: LegedsDaD/EasierBot/.github/workflows/bot-engine.yml@main
    
    secrets:
      APP_ID: ""
      APP_PRIVATE_KEY: ""
